version: '3.4'

services:
  ice.server:
    image: ${DOCKER_REGISTRY-}voxia/ice-server:latest
    build:
      context: .
      dockerfile: src/ice/VoxIA.ZerocIce.Server/Dockerfile
    ports:
      - "10000:10000"
      - "10001:10001"
      - "6000-6025:6000-6025"
    volumes:
      - ./data/tracks:/app/tracks
      - ./data/certs:/app/certs

  rasa.api:
    image: ${DOCKER_REGISTRY-}voxia/rasa-nlu-api:latest
    build:
      context: .
      dockerfile: src/nlu/rasa/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - MODEL_FILE="nlu-20210507-144512.tar.gz"

  speechbrain.api:
    image: ${DOCKER_REGISTRY-}voxia/speechbrain-api:latest
    build:
      context: .
      dockerfile: src/asr/speechbrain/Dockerfile
    ports:
      - "5000:80"