version: '3.4'

services:
  ice.server:
    image: ${DOCKER_REGISTRY-}voxia/ice-server:latest
    build:
      context: .
      dockerfile: src/ice/VoxIA.ZerocIce.Server/Dockerfile
    ports:
      - "10000:10000"

  rasa.api:
    image: ${DOCKER_REGISTRY-}voxia/rasa-nlu:latest
    build:
      context: .
      dockerfile: src/nlu/rasa/Dockerfile