version: '3.4'

services:
  ice.grid.registry:
    image: zeroc/icegridregistry
    ports:
      - "4061:4061"
      - "4062:4062"
    expose:
      - "20000"
      - "20001"
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    depends_on:
      - ice.grid.node1
      - ice.grid.node2
    volumes:
      - ./src/ice/VoxIA.ZerocIce.Server/config.registry:/etc/icegridregistry.conf:ro
      - ./data/icegrid/registry:/var/lib/ice/icegrid

  ice.grid.node1:
    image: ${DOCKER_REGISTRY-}voxia/ice-node:latest
    build:
      context: .
      dockerfile: src/ice/VoxIA.ZerocIce.Server/Dockerfile.node
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP-127.0.0.1}
      - STREAMING_PORT_RANGE_MIN=${STREAMING_PORT_RANGE_MIN-6000}
      - STREAMING_PORT_RANGE_MAX=${STREAMING_PORT_RANGE_MIN-6024}
    ports:
      - "10000-10001:10000-10001"
      - "6000-6024:6000-6024"
    expose:
      - "20002"
      - "4061"
      - "4062"
    volumes:
      - ./src/ice/VoxIA.ZerocIce.Server/config.node1:/etc/icegridnode.conf:ro
      - ./data/icegrid/node:/var/lib/ice/icegrid
      - ./data/tracks:/app/tracks
      - ./data/certs:/app/certs

  ice.grid.node2:
    image: ${DOCKER_REGISTRY-}voxia/ice-node:latest
    build:
      context: .
      dockerfile: src/ice/VoxIA.ZerocIce.Server/Dockerfile.node
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - STREAMING_PORT_RANGE_MIN=${STREAMING_PORT_RANGE_MIN-6025}
      - STREAMING_PORT_RANGE_MAX=${STREAMING_PORT_RANGE_MIN-6049}
    ports:
      - "10002-10003:10002-10003"
      - "6025-6049:6025-6049"
    expose:
      - "20002"
      - "4061"
      - "4062"
    volumes:
      - ./src/ice/VoxIA.ZerocIce.Server/config.node2:/etc/icegridnode.conf:ro
      - ./data/icegrid/node:/var/lib/ice/icegrid
      - ./data/tracks:/app/tracks
      - ./data/certs:/app/certs

  rasa.api:
    image: ${DOCKER_REGISTRY-}voxia/rasa-nlu-api:latest
    build:
      context: .
      dockerfile: src/nlu/rasa/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - MODEL_FILE="nlu-20210507-144512.tar.gz"

  speechbrain.api:
    image: ${DOCKER_REGISTRY-}voxia/speechbrain-api:latest
    build:
      context: .
      dockerfile: src/asr/speechbrain/Dockerfile
    ports:
      - "5000:80"
    environment:
      - MODEL_LANG=en