version: '3.4'

services:
  ice.server:
    image: ${DOCKER_REGISTRY-}voxia/ice-server:latest
    build:
      context: .
      dockerfile: src/ice/VoxIA.ZerocIce.Server/Dockerfile
    ports:
      - "10000:10000"
      - "6000-6025:6000-6025"
    volumes:
      - ./data/tracks:/app/tracks

  rasa.api:
    image: ${DOCKER_REGISTRY-}voxia/rasa-nlu:latest
    build:
      context: .
      dockerfile: src/nlu/rasa/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - MODEL_FILE="nlu-20210507-144512.tar.gz"

volumes:
  data-tracks: